name: NPM Publish (Dev)
on:
  push:
    branches:
      - main
jobs:
  npm-publish-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Run final tests
        # npm run test is excluded here intentionally
        run: npm run lint && npm run prettier

      - name: Deprecate old versions
        run: npm deprecate quickpostgres@"~$(jq --raw-output '.version' package.json)" "no longer supported" || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(date +%s).$(git rev-parse --short HEAD)
          npm publish --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
